### ISSUE TITLE
1024x1024 model question

### ISSUE THREAD

**Issue by zelenooki87** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#12]
Hi. Do you plan to release 1024x1024 model?
Or it can be done modifying code to cascade all models?
Cause, I think it is better to not downscale images to 128Pixels.
Thank you very much in advance

**Comment by Janspiry** [comment]
1. 1024x1024 model
According to the 64 to 512 super-resolution task, it needs a large mount of model parameters to recover adequate images information. I am afraid not to train 1024x1024 super-resolution model since GPU devices limitation in a short time. 
2. cascade all models
For the current pre-trained models, it can not be cascaded directly. You may need to train yourself for new tasks : )

**Comment by zelenooki87** [comment]
ok.
could you please tell me, how to test your code on 512Px cropped face images without downscale them if possible. Thanks

**Comment by Janspiry** [comment]
I did not understand it, which means to upscale a 512x512 images to more higher resolution one?

**Comment by zelenooki87** [comment]
I already cropped faces with onother project(GFPGAN) to 512Pix. Now, what I want is to try your code on those images without changing resolution. I want enhance faces to be in same resolution (512x512pixels). Then I will pasteback those faces directly from GFPGAN. If it is not possible, please tell me ways I can do it. If output face photo must be upscaled, no problem, I will downscale it with photoshop.

**Comment by Janspiry** [comment]
I see. You can directly execute tasks in 512Pixels images, since the model get a super-resolution result from 512Pixels" low-resolution" image. You should change the config  to `"mode": "HR", // whether need LR img` and commented all code about 
 **LR** or **lr** like`lr_img = Metrics.tensor2img(visuals['LR']); ` in sr.py.

**Comment by zelenooki87** [comment]
when I commented that line everything goes OK until
21-09-12 15:40:59.820 - INFO: Begin Model Evaluation.
sampling loop time step: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2000/2000 [05:54<00:00,  5.64it/s]
Traceback (most recent call last):
  File "C:\Users\KaMi\SR3\sr.py", line 150, in <module>
    hr_img = Metrics.tensor2img(visuals['HR'])  # uint8
TypeError: 'NoneType' object is not subscriptable

**Comment by Janspiry** [comment]
![image](https://user-images.githubusercontent.com/32922494/132990332-337a18d6-eb8d-4793-a418-54327db35a27.png)
Actually we take 512Pixel image as SR and ignore LR, but we also need HR to calculate SSIM in vanilla method. You can commented all code about SR or copy SR image to HR image as ground truth.

**Comment by zelenooki87** [comment]
I successed it. But with model that correspond 64x512 results are too sharp and not much better from original.
Could you please suggest me which model best suits my case? Or how to upscale photos other than 512 pixels? is that possible?
thanks

**Comment by Janspiry** [comment]
I think this has something to do with the unstable pre-trained model. I have some suggestion  about it:
1. retrain it with adequate model parameters.
2. sample from SR rather than random noise in validation, which need change the code `img = torch.randn(shape, device=device)` to `img = x` in sr3_modules/diffuision.py, Line 191, then adjust the timesteps range. 
3. use more timesteps than 2000 directly.
4. use other super-resolution model.

**Comment by lmvgjp** [comment]
Hi,
I tried your implementation and faced the problems of zelenooki87.
As you have experience in the field, can you please recommend other super-resolution model in particular that could work for this task?
Thanks a lot for your awsome code!

**Comment by Janspiry** [comment]
So sorry, I didn't know much about other models. 
Maybe you can get them by rank in the `https://www.paperswithcode.com/` or the SOTA in some papers.

**Comment by lmvgjp** [comment]
thank you very much for your reply, Janspiry!

**Comment by AndreyStille** [comment]
> Hello, thank you so much for your helpful reply! Very kind of you! Greetings

Hi 
Can you please give some advice if you have succeeded with your task? What beta schedule have you used? 
I'm trying to train 256->1024, with quite big dataset, loss is reducing but validation result same as after first epoch.

**Comment by lmvgjp** [comment]
Hi 
I could not make it work, sorry...the result was too noisy...I think the model needed much more images than i gave it.
I got good super-resolution results directly with this pretrained model, without training it myself:
https://github.com/yangxy/GPEN
