### ISSUE TITLE
n_timestep setting

### ISSUE THREAD

**Issue by wentaoxia** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#67]
Hi , I try to set "n_timestep" of val  phase different values and found that  when "n_timestep"  become large (over 50000),  
<img width="660" alt="截屏2022-06-09 上午9 31 00" src="https://user-images.githubusercontent.com/45745731/172745085-22c713b8-12ec-4e4d-86e3-6bf5b1595a30.png">

sr.py or inter.py cannot output a normal image and I check the output of p_sample in diffusion.py is NAN.  Is it true? 
<img width="516" alt="截屏2022-06-09 上午9 31 52" src="https://user-images.githubusercontent.com/45745731/172745170-4f1d8f18-b247-4c48-b9cc-a9dafc85a49e.png">

And how to get a normal output when n_timestep is set a large value?
Excellent job!  Thanks so much!

**Comment by Janspiry** [comment]
![image](https://user-images.githubusercontent.com/32922494/173237700-8c0f7b1b-86c7-4a93-9e54-b53e55dd6e53.png)
I think there are two factors that contribute to this phenomenon:
1. The gap between training and testing steps is too large.
2. When the timesteps is too large, the gamma_t tends to 0 because of too many times of continuous multiplication

**Comment by wentaoxia** [comment]
Got it ! Thanks for your reply!
